apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook-applicationset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - "missingkey=error"
  generators:
    - git:
        repoURL: https://github.com/iampraveennt/docker-desktop-k8s-apps.git
        revision: main
        files:
          - path: deployments/dev/us-east1/*/app.yaml
        values:
          rootdir: "{{ index .path.segments 0}}"
          env: "{{ index .path.segments 1}}"
          region: "{{ index .path.segments 2}}"
          appname: "{{ index .path.segments 3}}"
  template:
    metadata:
      name: "{{ .values.env }}-{{ .values.appname }}"
    spec:
      source:
        repoURL: "{{ .default.spec.source.repoURL }}"
        targetRevision: "{{ .default.spec.source.targetRevision }}"
        path: "{{ .default.spec.source.path }}"
      destination:
        name: in-cluster
      project: guestbook-project
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

