default:
  spec:
    source:
      repoURL: https://github.com/argoproj/argocd-example-app.git
      targetRevision: HEAD
      path: guestbook
    destination:
      name: in-cluster
      namespace: guestbook
