apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook-application
  namespace: argocd
spec:
  destination:
    namespace: helm-guestbook
    name: {{ .Values.spec.destination.name }}
  project: application-set-project
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: helm-guestbook
    helm:
      releaseName: helm-guestbook
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true