apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: app-of-app
spec:
  destination:
    name: in-cluster
    namespace: guestbook
  project: application-set-project
  source:
    repoURL: https://github.com/iampraveennt/docker-desktop-k8s-apps.git
    targetRevision: HEAD
    path: apps
    helm:
      releaseName: app-of-apps